### PR TITLE
Update android.md

### PR DESCRIPTION
**Pull request by thebunnyrules**
* Removed ant as a build requirment and added gradle.
* android update project no longer works, so I removed those lines.
* added instructions on how to sign apks for release builds.
* added clarifications on core building and instructions on how to build individual cores

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
This looks good so far, but I have a comment from the guy who overhauled all of the Android scripts:

>  It's worth pointing out that not all android cores use jni. Some are cmake, and iirc one of the mame is still using makefiles

**Comment by thebunnyrules** [comment]
That's good know. Can he give me some example of the commands so that I may
update the docs accordingly?

I'm also having trouble to get the compiled apk to load the cores. Has the
core location changed from phoenix/assets/cores ?

>

**Comment by hizzlekizzle** [comment]
I think it's enough just to mention that what you have applies to most cores, though a handful may use other methods, such as cmake or a static makefile.

For core location, I believe it's /data/data/com.retroarch/cores.

**Comment by thebunnyrules** [comment]
it was more for my own benifit that I was asking about the commands but
that's ok, I'll mention cmake and make in the docs.

**Comment by thebunnyrules** [comment]
I've updated the docs. I might have another go at them for grammar and
style but should be about it after that...

**Comment by thebunnyrules** [comment]
Ok, I've finished touching it up. It's ready for merge. Please let me know
if anything needs to be fixed.

**Pull request merged**
