### PR TITLE
migrate and update CLI guide, clarify playlist info

### PR DESCRIPTION
**Pull request by markwkidd**

### CODE REVIEW

**Comment by thatman84** [comment]
@markwkidd

Couple of minor edits

Cli-intro.md
"RetroArch is composed of robust graphical interfaces as well as a powerful and a command-line interface (CLI)."

Edit
RetroArch is composed of robust graphical interfaces as well as a powerful command-line interface (CLI).

**Comment by thatman84** [comment]
Roms-playlist-thumbnails.md

**You can omit a link to the database for a manualy playlist entry by using the word DETECT here instead.**

Edit
**You can omit a link to the database for a manualy created playlist entry by using the word DETECT here instead.**

**Comment by markwkidd** [comment]
Thanks for the catches @thatman84 ! Fixed

**Comment by thatman84** [comment]
Nice, NP

**Pull request merged**
