### PR TITLE
New readme for DOSBox Pure

### PR DESCRIPTION
**Pull request by mrmatteastwood**
Hello, Libretro team! Over the past one and a half years, I and @schellingb have been working on a documentation for the core, DOSBox Pure. Today, it's finally done and we hope you will consider adding it to the Libretro Docs library (https://docs.libretro.com/) in _For Users_ > _Core Library: Emulation_ > _DOS Emulation_.

I hope this is the correct way to do this. I see a message at the top here saying, "Can’t automatically merge. Don’t worry, you can still create the pull request." The file I'm submitting is [dosbox-pure.md](https://github.com/mrmatteastwood/docs/blob/DOSBox-Pure-doc-WIP/docs/library/dosbox-pure.md). Let me know if there's anything else you need.

### CODE REVIEW

**Comment by fpscan** [comment]
Hi, this is great and I'm happy to merge it but I wanted to ask main dev for their inputs. Since this is contains so many changes.

**Comment by mrmatteastwood** [comment]
Hey @fpscan, thanks for your quick reply. @schellingb is DOSBox Pure's main dev, and you can see my discussion thread for the readme with him here: https://github.com/schellingb/dosbox-pure/issues/50

In case you meant the RetroArch main devs, of course I'm happy to wait. Thanks again! :-)

**Comment by schellingb** [comment]
@fpscan As mentioned I have given my inputs during the creation of this document and have read through the final version and I think it's good.

I don't know if there are any standards or rules core documentations adhere to and if ours is too detailed or in some other way weird but assuming not, the file `dosbox-pure.md` here can be merged as is.

If the PR is weird because its branch was forked a long time ago or if the large amount of small commits is too much, maybe a new branch could be created with just a single commit of the entire new file and submitted in a new PR?

**Comment by fpscan** [comment]
@schellingb Hi, the changes are great and I'm happy to merge however it has conflicts that need to be resolved by @mrmatteastwood I suggested to when fork and upstream even make new branch and carry over the changes to new branch. I could make the changes on my end and mention " these changes made by @mrmatteastwood " if it's okay?

**Comment by mrmatteastwood** [comment]
Hey guys! @fpscan Yes, if you have any way of simply taking my dosbox-pure.md and adding it to the main repo, that would be awesome. I'm not really good at GitHub, I have only very basic knowledge of how it works, but I can assure you I made no changes to any other files in the repo, only added dosbox-pure.md and worked on it with @schellingb over the past 1.5 years. :-)

**Comment by fpscan** [comment]
Here is the page and it looks great! https://docs.libretro.com/library/dosbox_pure/ Thank you for the changes. I'll close this PR now.

**Comment by mrmatteastwood** [comment]
Awesome! Thanks so much!

**Pull request closed without merging**
