### PR TITLE
new guide: "Getting Started with Arcade Emulation"

### PR DESCRIPTION
**Pull request by markwkidd**
This new guide is based on similar work that I helped with for the RetroPie docs, and the reason for adding it here is the same.

The goal is to help people avoid the major pitfalls of libretro arcade emulation before they get frustrated or give up. It is written assuming that the user has never worked with an arcade emulator, so they would not be familiar with some key concepts like the fact that romsets must be built to match the specific emulator they are using.

In other words, the guide is intended to address the most common sources of frustration for users who are getting started with arcade emulation. It's based on what I've learned (and what other folks have learned) from many support threads and discord posts.

That is not to say that this text cannot be improved! @hizzlekizzle looked at a slightly earlier draft and may have input on this version. I'd appreciate feedback from him or anyone else with what I've submitted here.

### CODE REVIEW

**Comment by thatman84** [comment]
Looks good

I don’t have any comments other than the page location/title. It doesn’t really fit under Core docs imo on other headings either.

Not a big issue though. It could easily go in it’s own heading but that may not sit well with others

For example

For Users
     General Emulation Topics

**Comment by markwkidd** [comment]
I didn't know where best to locate this guide in the table of contents and I am very much open to changing the current location.

**Comment by thatman84** [comment]
Yeah I am of the same view although being inactive I don’t want to make the decision lol

It would be nice to see a couple more topics like this in the future to make it a valid sub section. 

Maybe Create a new section “Core Selection Tips” along side Core Documentation or nested within Core Documentation 
This is a reasonable topic that many users don’t understand.

**Comment by hizzlekizzle** [comment]
Looks good to me. I'll go ahead and merge it and we can move it around later if needed.

**Pull request merged**
