### PR TITLE
add guide to video recording/streaming

### PR DESCRIPTION
**Pull request by markwkidd**

### CODE REVIEW

**Comment by twinaphex** [comment]
Seems this needs to be resolved.

**Comment by thatman84** [comment]
I do have a little but not used It for a year or so.

What do you need?

**Comment by CuttleFishJones8652** [comment]
Guides and resources

**Comment by thatman84** [comment]
I will take a look over the weekend and see what I can remember :)

**Comment by thatman84** [comment]
Found a handy resource.  Configuration file details. Not sure if everything is supported in the core. Posting here for reference later

https://github.com/libretro/PUAE/blob/master/docs/configuration.txt

**Pull request closed without merging**
