### PR TITLE
create guide to overlays

### PR DESCRIPTION
**Pull request by markwkidd**
I was trying to learn how these worked today and I didn't see anything written about overlays yet in the docs, so here is the first start.

Note that it is still vague on actually using them, due to the fact that I'm still vague :1st_place_medal: 

@hizzlekizzle tagging you since the overlay repo you manage gets a namecheck

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
good start!

The overlay spec page is also useful for reference:
https://docs.libretro.com/specs/overlay/

Another difference between shaders and overlays is that shaders can only affect the game's viewport while overlays can affect the entire screen (including the black borders around 4:3 images).

There's also a buttload of borders in this repo:
https://github.com/libretro/overlay-borders

**Comment by markwkidd** [comment]
Incorporated!

**Comment by markwkidd** [comment]
@thatman84 I just pulled up a google cache of your emulation guide site -- I can see that I'm moving into your domain here. I'll link to your site at the bottom of the doc at the least!

**Comment by hizzlekizzle** [comment]
Just let me know when you're ready to merge this and I'll get it done.

**Comment by markwkidd** [comment]
The only thing I'm not sure about yet is how to actually turn on a dang overlay, lol

I need to get back to my home PC and try this out

**Comment by thatman84** [comment]
Settings->Onscreen Display
Point to the config file

**Comment by thatman84** [comment]
here is my info on the subject. Screenshots are outdated now http://www.emulationguide.com/retroarch-overlays.html

site is back up in a fashion :)

**Comment by markwkidd** [comment]
Thanks again @hizzlekizzle and @thatman84 ! I have added some new content and I think I'm ready to call it quits on this. What do you think?

I know it could still use a bit more work but if you see any showstoppers definitely let me know.

**Comment by hizzlekizzle** [comment]
oh whoops, looks like I can't merge stuff here. We'll have to wait for someone else with privs.

**Comment by inactive123** [comment]
@hizzlekizzle Going to give you merge permissions too.

**Pull request merged**
