### PR TITLE
add WIP software list guide

### PR DESCRIPTION
**Pull request by thatman84**
Not sure when I will get back to it and avoiding diverged issues i'm not up to speed with

### CODE REVIEW

**Comment by markwkidd** [comment]
Thanks again for this. I don't use software list roms (or haven't yet anyway) but I'm sure this is going to help a lot of people

**Comment by hizzlekizzle** [comment]
this looks good, but I see the word "varient" a few times, which is a misspelling of "variant". Get that fixed up and I'll merge it.

**Comment by thatman84** [comment]
@hizzlekizzle I updated those errors, not sure how this works now with diverged.

I did update my repo with the additions so now my pull request has those. I will try and catch you on discord for advice

**Comment by markwkidd** [comment]
everything looks right to me on the git side. there are no merge conflicts.

**Pull request merged**
