### PR TITLE
add new BIOS and font roms

### PR DESCRIPTION
**Pull request by trapexit**

### CODE REVIEW

**Comment by RobLoach** [comment]
Mind updating the .info file over at https://github.com/libretro/libretro-super/blob/master/dist/info/4do_libretro.info ?

It's capable of checking BIOS files. Can list optional ones too.

**Comment by trapexit** [comment]
Sure but does it support 1 of N being required? I can make them all optional if not.

**Comment by RobLoach** [comment]
Hmmm, tricky. Unsure of the syntax, actually.

**Comment by trapexit** [comment]
I updated the info file and it was merged.

**Review by RobLoach — APPROVED** [review]
This is great!

screenshot at 2018-06-25 16-25-20

**Pull request merged**
