### PR TITLE
removed banner image paths, core_template edit & mgba edit

### PR DESCRIPTION
**Pull request by thatman84**
removed image path for banners

bug tracker edit to core_template.md

bug tracker edit to mgba.md

### CODE REVIEW

**Comment by twinaphex** [comment]
Why did you remove the banners though? I thought it was a nice touch.

**Comment by fr500** [comment]
I asked him,  we don't own the names in any way nor the right to use them.

I'm trying to get a full featured uniform looking site for docs

**Comment by twinaphex** [comment]
It's fair use to use a logo like that IMHO. Why be more legal-esque about this stuff than a lawyer really?

**Comment by fr500** [comment]
The banners look ugly in the page and they take a lot of space for literally no reason.
If you disagree, feel free to revert.

**Comment by twinaphex** [comment]
Nah, that wont ge necessary. I trust that you will make the right decisions for this repo instead, so yes, the banners can remain gone.

**Pull request merged**
