### PR TITLE
convert/update core development docs

### PR DESCRIPTION
**Pull request by markwkidd**
Here I have converted the "Implementing the Core" and the OpenGL core development doc to markdown and updated them lightly.

The "Rate Control" doc has a substantial amount of formulas which won't translate easily to markdown, so I'm attempting to link it into the table of contents as a PDF. Let's see how that goes with mkdocs.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
How about screenshotting the formulas and embedding them in the markdown?

**Comment by markwkidd** [comment]
@hunterk I don't mind doing some screenshot work but the formulas are pervasive throughout the doc: https://github.com/libretro/docs/blob/master/archive/ratecontrol.pdf

I can justify spending an hour or two on this but seems like I would need a convention for converting at least some of the in-paragraph formulas to text and markdown because taking shots of everything would be unwieldy.

Would you consider merging this PR and then letting me work on a new PR just for the Rate Control Doc?

If there are no other issues with this PR I would be glad to have it merged either with or without adding the PDF link to the table of contents -- no strong feelings on that especially if we are going to try to make it into Markdown.

**Comment by hizzlekizzle** [comment]
ah, yeah, that's more trouble than it's worth. I'm fine with just linking the PDF.

**Comment by markwkidd** [comment]
Fair enough, thanks!

I have not tried to link a PDF here before nor does it look like there are any others, so I'll double check once the docs rebuild to see how the link was parsed. I'm ready whenever convenient.

**Pull request merged**
