### PR TITLE
Update install-psp.md

### PR DESCRIPTION
**Pull request by FieryMewtwo**
Better grammar and better directions

### CODE REVIEW

**Comment by fpscan** [comment]
Can we just have the [installation ](https://github.com/libretro/docs/pull/680/files#diff-0f4878429c8e0738bc38f18ebdb8df3846c9888104d8fd01249cdac60c974000R20)section and not the rest?

**Comment by FieryMewtwo** [comment]
> Can we just have the [installation ](https://github.com/libretro/docs/pull/680/files#diff-0f4878429c8e0738bc38f18ebdb8df3846c9888104d8fd01249cdac60c974000R20)section and not the rest?

Done.

**Comment by fpscan** [comment]
@FieryMewtwo hi, could you send new pr with changes(just grammar part)

**Comment by FieryMewtwo** [comment]
Sure!

**Pull request merged**
