### PR TITLE
standardize development doc paths

### PR DESCRIPTION
**Pull request by markwkidd**
I realize that this change will alter the paths of some docs and I don't make it lightly. Given the success of our docs and how they are expanding, I believe now is a good time to standardize the paths of the docs.

This PR sorts "For Developer" docs which are outside the `development` folder into that root path.  It would probably also be good to sort the "User" docs under a folder but that is a bigger project I might take on separately :)

### CODE REVIEW

**Comment by hhromic** [comment]
just wanted to say that I really appreciate what you are doing with improving the development docs @markwkidd ,  this is really useful and cornerstone for the libretro ecosystem to flourish more.

**Comment by markwkidd** [comment]
You're welcome @hhromic and thank you for saying that! :)

**Comment by inactive123** [comment]
A merge conflict has to be resolved here before it can be merged.

**Comment by markwkidd** [comment]
@twinaphex thank you -- it should be fixed now

**Comment by inactive123** [comment]
Still a merge conflict.

**Comment by markwkidd** [comment]
@twinaphex I guess it's because I added the Coding Standards doc to the TOC. fixed now

**Comment by markwkidd** [comment]
The way this PR is constructed it is constantly leading to merge conflicts. I'm going to close and resubmit a cleaner PR with the exact same changes.

**Pull request closed without merging**
