### PR TITLE
Update scummvm.md

### PR DESCRIPTION
**Pull request by CuttleFishJones8652**
- Sync ScummVM with core template.
- Cleaning up the ScummVM doc so @jdgleaver has an easier time updating it with the Gamepad changes.

### CODE REVIEW

**Comment by jdgleaver** [comment]
@Hedonium - thank you for this :slightly_smiling_face:

Once I've finished tweaking the core, I plan to make some substantial additions to the ScummVM documentation - it currently omits a bunch of information regarding essential auxiliary data files and configuration settings, which makes the core rather inscrutable for inexperienced users.

**Comment by thatman84** [comment]
I am going through testing ScummVM games right now on Shield TV if its
anyhelp. (Only launch testing right now though, nothing to detailed)

https://docs.google.com/spreadsheets/d/1a87BnQJc7_fTD5zF55JXcm79d5_l_d1ghDxtiubTnDE/edit?usp=drivesdk

I will keep an eye out for the updates and see if it sheds light on some of
my issues.

**Comment by jdgleaver** [comment]
That spreadsheet is excellent - if it's okay with you, I'll link to it in the 'compatibility' section of the docs.

I'm not going to touch the engine code, so there won't be bug fixes (just a couple of feature additions) - but I will prepare a bundle containing all required extra data files, the 'scummmodern' theme and a default soundfont (for MIDI emulation) which users can drop in their 'system' directory (and I'll provide instructions for configuring the core to use these files).

Oh, and here are some extra notes for your spreadsheet:

- Working games:

    - sky : Beneath a Steel Sky (CD VGA)

    - tentacle : Day Of The Tentacle (CD DOS)

    - dw-cd : Discworld (1995)(Psygnosis) [note: requires retail copy + v1.04 patch for correct operation]

    - queen : Flight of the Amazon Queen (CD DOS) [note: can crash RetroArch if you try to close the core during the initial cutscene]

    - ft : Full Throttle (CD DOS)

    - atlantis : Indiana Jones and the Fate of Atlantis (CD DOS VGA)

    - indy3 : Indiana Jones and the Last Crusade (Floppy DOS VGA)

    - loom : Loom (CD DOS VGA)

    - comi : The Curse Of Monkey Island (CD Windows)

- Non-working games:

    - dreamweb : Dreamweb, Freeware CD DOS Version (English UK) [Black screen at launch + eventual freeze]

- Other notes:

    - monkey2: you don't need the code from the manual - any (random) code will work

    - nippon: needs code from manual to play past the intro + 'Nippon Safes Inc (Amiga, Multilanguage)' version does have sound (although it is used very sparingly)

**Comment by thatman84** [comment]
Awesome stuff, yeah I am trudging through to a custom database based on the
2.0 compat list.

I plan on going back over the notes to double check.

**Pull request merged**
