### PR TITLE
[READY] Update controller-autoconfiguration.md: Documented the new _alt autoconfig variables

### PR DESCRIPTION
**Pull request by davidhedlund**
* https://github.com/libretro/RetroArch/pull/16990

### CODE REVIEW

**Comment by davidhedlund** [comment]
By chance, I connected a different controller via Bluetooth before this pull request was approved. It turns out that the Bluetooth issue was related to the operating system, not the Nintendo Switch Pro Controller that I added to the example table.

**Comment by landfillbaby** [comment]
```md
this is the proper footnote[^1] syntax.

[^1]: reference.

bla bla bla.
```
gives:

this is the proper footnote[^1] syntax.

[^1]: reference.

bla bla bla.

**Comment by davidhedlund** [comment]
> ```
> this is the proper footnote[^1] syntax.
> 
> [^1]: reference.
> 
> bla bla bla.
> ```
> 
> gives:
> 
> this is the proper footnote[1](#user-content-fn-1-31688730a5b5039dc7c70288cac93c1d) syntax.
> 
> bla bla bla.
> ## Footnotes
> 
>     1. reference. [↩](#user-content-fnref-1-31688730a5b5039dc7c70288cac93c1d)

Solved, thanks.

**Comment by davidhedlund** [comment]
> ```
> this is the proper footnote[^1] syntax.
> 
> [^1]: reference.
> 
> bla bla bla.
> ```
> 
> gives:
> 
> this is the proper footnote[1](#user-content-fn-1-c60bca39be55506ba5941655e7857121) syntax.
> 
> bla bla bla.
> ## Footnotes
> 
>     1. reference. [↩](#user-content-fnref-1-c60bca39be55506ba5941655e7857121)

Can you please assist me in https://github.com/libretro/docs/pull/982?

Best

**Comment by davidhedlund** [comment]
@fpscan This PR has been ready for a while now. Can you please merge it?

**Comment by davidhedlund** [comment]
@fpscan I just solved the conflict. It's ready to be merged now.

**Pull request merged**
