### PR TITLE
add preliminary homepage and 4DO core.

### PR DESCRIPTION
**Pull request by HerbFargus**

### CODE REVIEW

**Comment by twinaphex** [comment]
@HerbFargus Hmm, I have to be honest, I don't like that logo or at least the type font.

That is the only thing I don't like - the rest is great. If you could replace that logo with the original, I'd be fine with that.

**Comment by twinaphex** [comment]
EDIT: Replaced the logo already.

**Comment by thatman84** [comment]
FYI Core_Template is missing RetroPad_L2.png in images directory. not sure where those are from otherwise i would add it

**Comment by HerbFargus** [comment]
@twinaphex yeah it was just thrown in as a placeholder as I know there has been some discussion on the logo, so no worries

@thatman84 tbh I can't say I'm all that fond of the current retropad buttons icons, I just pulled them from the libretro wiki and that didn't have L2 either though I imagine they were generated in some form from the icon set I mentioned here: https://github.com/libretro/docs/pull/10 but I don't have any Adobe tools to convert the fla files to svgs (I prefer to work wit svgs) 

The other idea is to do away with the chart and just have image diagrams with the retropad with lines drawn the buttons on the original gamepad like so:

**Comment by fr500** [comment]
We really need an official retropad art...
I used XBOX 360 as a basis for many docs too but it feels off.

I don't like the charts with lines personally

**Comment by HerbFargus** [comment]
@fr500 yeah it was just an idea. I'm fine either way. We have a talented artist that does stuff for retropie, I could ask him if he wanted to come up with something for the retropad (svg of course) is there a set of guidelines or an idea of what you want?

**Comment by fr500** [comment]
There were some concepts in the assets repo already... I don't really know but if he can throw some concepts it would be cool

**Comment by thatman84** [comment]
I'm also not keen on linked double picture although its beeter than the columns for conveying the controls if your not familiar with the system controller. My though would be to have the retropad nailed done with decent button images. Then have the system controller with the retropad images surrounding it references. This would keep the images required to a minimum. I will ask all artists I know if anyone has the time to help

**Comment by thatman84** [comment]
Phone typing apologies for mistakes

**Comment by twinaphex** [comment]
@HerbFargus Excellent work BTW on the controller diagram and how the buttons relate to the RetroPad. I hope we can eventually have a docs page for most cores with a diagram for each of them, that would really help. Especially if we could later on use those same pictures for RetroArch itself.

**Pull request merged**
