### PR TITLE
add xml shader doc to development doc TOC

### PR DESCRIPTION
**Pull request by markwkidd**
@hunterk how many shader specs are there?!? 👹 

At any rate, AFAIK this is the fourth and final shader spec to add to the development docs

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I believe the XML shaders are no longer valid (that is, no just deprecated, but no longer able to be loaded), though the spec may be useful for historical purposes.

**Comment by markwkidd** [comment]
There is some text to that effect added to the TOC and the XML shader doc itself with this PR but maybe you should see if it is clear enough.

**Comment by markwkidd** [comment]
Actually let me make it stronger, give me a second

**Comment by markwkidd** [comment]
@hizzlekizzle I've made the warning about the XML shaders a little stronger in the last commits I pushed

**Pull request merged**
