### PR TITLE
Start a glossary and explain Salamander

### PR DESCRIPTION
**Pull request by TobiX**
I started this because I spent some time wrapping my head around the different "build types" - I still hope I can motivate someone else to explain "griffin" to me :D

(I'm open to call the page something different, "concepts" was the first word that came to mind)

### CODE REVIEW

**Comment by fpscan** [comment]
Hi,

This is great, can we call anything else?

edit: Methods?

**Comment by hizzlekizzle** [comment]
Yes, this is a good idea. I noticed a couple of typos, though:

> ~~This~~ **These** are some concepts used in RetroArch, which might be unfamiliar to new developers.
> 
> ...
> 
> Salamander is a small RetroArch launcher for embedded platforms with static linking. On such platforms, each core binary contains the core and the complete RetroArch frontend. Switching cores is ~~achived~~ **achieved** by just re-launching into a different core binary. Salamander simply ~~laucnches~~ **launches** the most...

**Comment by TobiX** [comment]
How about calling it "glossary" or maybe expand it a bit more and call it "code/repository structure"?

**Comment by fpscan** [comment]
> glossary

That's sounds more cooler than what I suggest :) @hizzlekizzle has more linguistics knowledge than anyone I know, so I guess he is going to make final.

**Comment by hizzlekizzle** [comment]
glossary works for me.

**Comment by TobiX** [comment]
Updated. Not sure about the intro text, but it's a start :D

**Review by fpscan — APPROVED** [review]
Yeah, definitely, this the start that encourage the people. Since Hunter didn't say otherwise and I guess this is good to go and thank you again.

**Pull request merged**
